In [435]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets,linear_model

In [436]:
housing=pd.read_csv("HousingData.csv")

In [437]:
from sklearn.model_selection import train_test_split
train_data,test_data=train_test_split(housing,test_size=.2,random_state=42)
print(len(train_data),"",len(test_data),"",len(housing))

404  102  506


In [438]:
print(train_data)

         CRIM    ZN  INDUS  CHAS     NOX     RM   AGE     DIS  RAD  TAX   
477  15.02340   0.0  18.10   0.0  0.6140  5.304  97.3  2.1007   24  666  \
15    0.62739   0.0   8.14   0.0  0.5380  5.834  56.5  4.4986    4  307   
332   0.03466   NaN   6.06   0.0  0.4379  6.031  23.3  6.6407    1  304   
423   7.05042   0.0  18.10   0.0  0.6140  6.103   NaN  2.0218   24  666   
19    0.72580   0.0   8.14   0.0  0.5380  5.727  69.5  3.7965    4  307   
..        ...   ...    ...   ...     ...    ...   ...     ...  ...  ...   
106   0.17120   0.0   8.56   0.0  0.5200  5.836  91.9  2.2110    5  384   
270   0.29916  20.0   6.96   0.0  0.4640  5.856  42.1  4.4290    3  223   
348   0.01501  80.0   2.01   0.0  0.4350  6.635  29.7  8.3440    4  280   
435  11.16040   0.0  18.10   0.0  0.7400  6.629  94.6  2.1247   24  666   
102   0.22876   0.0   8.56   0.0  0.5200  6.405  85.4  2.7147    5  384   

     PTRATIO       B  LSTAT  MEDV  
477     20.2  349.48  24.91  12.0  
15      21.0  395.62   8.47

In [439]:
housing=train_data.copy()
print(np.shape(train_data))

(404, 14)


                1->    train_index return index
                2->    strt_train to copy index in sets of data
                3-> n_splits return no sets we want

In [440]:
# from sklearn.model_selection import StratifiedShuffleSplit
# speel=StratifiedShuffleSplit(n_splits=1,test_size=.2,random_state=42)
# for train_index,test_index in speel.split(housing,housing.CHAS):
#     strt_train_data=housing.loc[train_index]
#     strt_test_data=housing.loc[test_index]

In [441]:
matrix_corr=housing.corr()
matrix_corr['MEDV'].sort_values(ascending=False)

MEDV       1.000000
RM         0.708231
B          0.339918
ZN         0.318554
DIS        0.235114
CHAS       0.199610
AGE       -0.359495
CRIM      -0.383800
RAD       -0.387467
NOX       -0.415768
TAX       -0.459795
INDUS     -0.465662
PTRATIO   -0.491210
LSTAT     -0.732602
Name: MEDV, dtype: float64

In [442]:
# from pandas.plotting import scatter_matrix
# attribute=["MEDV","RM","ZN","LSTAT"]
# scatter_matrix(housing[attribute],figsize=(10,10))

In [443]:
# housing.plot(kind='scatter',x='RM',y='MEDV')

Trying out Attribute combination

In [444]:
housing['TAXRM']=housing['TAX']/housing['RM']

In [445]:
# housing.head()

In [446]:
matrix_corr=housing.corr()
matrix_corr['MEDV'].sort_values(ascending=False)

MEDV       1.000000
RM         0.708231
B          0.339918
ZN         0.318554
DIS        0.235114
CHAS       0.199610
AGE       -0.359495
CRIM      -0.383800
RAD       -0.387467
NOX       -0.415768
TAX       -0.459795
INDUS     -0.465662
PTRATIO   -0.491210
TAXRM     -0.540606
LSTAT     -0.732602
Name: MEDV, dtype: float64

In [447]:
# housing.plot(kind="scatter",x='TAXRM',y='MEDV')

In [448]:
# housing.describe()

In [449]:
# print(np.shape(housing))

In [450]:
housing=train_data.drop("MEDV",axis=1)
housing_labels=train_data["MEDV"].copy()

                                    Missing Attribute

to take care of missing attribute we have 3 option

1 --> Get rid of the missing data points

2 --> Get rid of whole attribute

3 --> Set the value like mean,median,mode 

In [451]:
# Option 1
# a=housing.dropna(subset=["RM"])
# a.shape

In [452]:
# housing.describe()

In [453]:
# Option 2
# housing.drop("RM",axis=1).shape

In [454]:
# Option 3
# medium=housing.median()

In [455]:
# print(medium)

In [456]:
# housing["RM"].fillna(medium)
# Original dataframe are remain unchange 

                      Coping medium value to NA of "RM"  

In [457]:
from sklearn.impute import SimpleImputer
# imputer=SimpleImputer(strategy="median")
# imputer.fit(housing)

In [458]:
# imputer.statistics_

In [459]:
# fog=imputer.transform(housing)

In [460]:
# print(fog)

In [461]:
# housing_tr=pd.DataFrame(fog,columns=housing.columns)

In [462]:
# housing_tr.describe()

                                         Skcitk-learn Design

Primairaly 3-type of object
1. Estimation - It estiamte some parameter based on a datasets  eg.imputer
   It has fit and transform method
   fit methods -> fir the datsets and calculate the internal parameters

2. Transform - It takes input and give output based on learning from fit()
   It has convinions methos fit_transform which fit then transform

3. Prediction - LinearRegrssionModel are one of it's prdictor.fir() and transform() are it's function 

                               Feature Scaling

1. min-max Scaling(Normalization)
   (val-min)/(max-min)
   MinMaxScalar method

2. Standardization
   (val-mean)/std
   StandardScalar

In [463]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [464]:
my_pipeLine=Pipeline([
    ('imputer',SimpleImputer(strategy="median")),
    ('std_scl',StandardScaler())
])

In [465]:
housing_num=my_pipeLine.fit_transform(housing)

                                Model Training

In [466]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
# model=LinearRegression()
# model=DecisionTreeRegressor()
model=RandomForestRegressor()
model.fit(housing_num,housing_labels)

RandomForestRegressor()

In [467]:
some_data=housing.iloc[:5]
some_labels=housing_labels.iloc[:5]
prepared_data=my_pipeLine.fit_transform(some_data)
model.predict(prepared_data)

array([ 8.607, 22.497, 29.513, 27.363, 20.773])

In [468]:
list(some_labels)

[12.0, 19.9, 19.4, 13.4, 18.2]

                         Evaluating Error

In [469]:
from sklearn.metrics import mean_squared_error
housing_prediction=model.predict(housing_num)

lin_mse=mean_squared_error(housing_labels,housing_prediction)
lin_rmse=np.sqrt(lin_mse)

In [470]:
lin_rmse

1.5797643780320572

                                Cross-Validation

In [471]:
from sklearn.model_selection import cross_val_score
score=cross_val_score(model,housing_num,housing_labels,scoring="neg_mean_squared_error",cv=10)
rmse_score=np.sqrt(-score)

In [472]:
rmse_score

array([2.7727131 , 3.52747927, 3.8325489 , 5.52855663, 4.30903807,
       4.41231855, 4.11365062, 2.6347142 , 2.53960938, 4.9296245 ])

In [473]:
def anal_score(score):
    print("Score", score)
    print("Mean",score.mean())
    print("Standard_devaition",score.std())
    

In [474]:
anal_score(rmse_score)

Score [2.7727131  3.52747927 3.8325489  5.52855663 4.30903807 4.41231855
 4.11365062 2.6347142  2.53960938 4.9296245 ]
Mean 3.860025321620504
Standard_devaition 0.9506566403549525


                           Saving the Model

In [476]:
from joblib import dump,load
dump(model,'Dragon.joblib')

['Dragon.joblib']

In [482]:
X_test=test_data.drop("MEDV",axis=1)
Y_test=test_data["MEDV"].copy()
X_text_prepared=my_pipeLine.fit_transform(X_test)
final_predict=model.predict(X_text_prepared)
final_rms=mean_squared_error(Y_test,final_predict)
final_rmse=np.sqrt(final_rms)
print(final_predict,list(Y_test))

[25.44  33.984 17.627 24.526 16.221 21.575 20.133 17.432 21.453 20.75
 21.238 21.964  8.613 21.958 19.86  27.509 18.707  8.151 45.713 14.209
 29.811 27.433 15.589 24.666 14.542 15.012 20.226 15.717 21.042 20.249
 20.399 25.544 33.346 19.112 15.494 16.465 34.404 26.685 21.121 21.97
 19.806 33.062 46.363 18.501 26.619 13.46  16.844 26.06  18.424 30.631
 20.76  34.776 17.225 27.23  46.71  22.405 15.487 35.109 25.05  20.36
 28.882 43.521 31.485 19.173 29.242 19.719 13.585 23.862 31.623 15.315
 20.295 28.632  9.49  22.871 22.595  7.067 20.212 46.462  9.339 15.071
 20.707 12.168 20.006  9.274 20.875 28.716 21.367 27.024 25.176 22.571
 21.511  8.485 19.662 19.344 24.604 20.413 36.223 11.803 11.843 15.383
 21.142 22.715] [23.6, 32.4, 13.6, 22.8, 16.1, 20.0, 17.8, 14.0, 19.6, 16.8, 21.5, 18.9, 7.0, 21.2, 18.5, 29.8, 18.8, 10.2, 50.0, 14.1, 25.2, 29.1, 12.7, 22.4, 14.2, 13.8, 20.3, 14.9, 21.7, 18.3, 23.1, 23.8, 15.0, 20.8, 19.1, 19.4, 34.7, 19.5, 24.4, 23.4, 19.7, 28.2, 50.0, 17.4, 22.6, 15.1, 1

In [480]:
final_rmse

3.6568153843066726

In [481]:
prepared_data[0]

array([ 1.79167403,  0.        ,  1.21197852,  0.        ,  1.01173703,
       -1.75804373,  1.48680453, -1.00103851,  1.21786036,  1.22472125,
        0.22329795,  0.32916471,  1.31595014])